name: Send Message on Commit

on:
  push:
    branches:
      - main 

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Generate UUID
        id: generate_uuid
        run: |
          echo "UUID=$(uuidgen)" >> $GITHUB_ENV

      - name: Get Detailed Commit Information
        id: commit_info
        run: |
          echo "========================================"
          echo "AUTOMATED GITHUB ACTIONS MESSAGE:"
          echo "----------------------------------------"
          echo "Commit Author: ${{ github.actor }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Commit Message: ${{ github.event.head_commit.message }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Timestamp: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          # Get the stats of the commit
          git diff --stat ${{ github.event.before }} ${{ github.sha }} > commit_stats.txt || echo "No changes to report"
          cat commit_stats.txt
          echo "========================================"

      - name: Send message to API
        run: |
          COMMIT_STATS=$(cat commit_stats.txt)
          TIMESTAMP=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          MESSAGE="========================================\n"
          MESSAGE+="AUTOMATED GITHUB ACTIONS MESSAGE:\n"
          MESSAGE+="----------------------------------------\n"
          MESSAGE+="Commit made by ${{ github.actor }}: $COMMIT_MESSAGE\n"
          MESSAGE+="Commit SHA: ${{ github.sha }}\n"
          MESSAGE+="Repository: ${{ github.repository }}\n"
          MESSAGE+="Branch: ${{ github.ref }}\n"
          MESSAGE+="Timestamp: $TIMESTAMP\n"
          MESSAGE+="Changes:\n$COMMIT_STATS\n"
          MESSAGE+="========================================"
          
          # Ensure bubble_id is not missing
          BUBBLE_ID="4066670"
          if [ -z "$BUBBLE_ID" ]; then
            echo "Error: bubble_id is missing"
            exit 1
          fi

          # Create JSON payload
          JSON_PAYLOAD=$(jq -n \
            --arg bubble_id "$BUBBLE_ID" \
            --arg created_at "$TIMESTAMP" \
            --arg message "$MESSAGE" \
            --argjson messagemedia "[]" \
            --arg user_id "5302367" \
            --arg uuid "${{ env.UUID }}" \
            '{bubble_id: $bubble_id, created_at: $created_at, id: $id, message: $message, messagemedia: $messagemedia, user_id: $user_id, uuid: $uuid}')
          
          # Print the JSON payload for debugging
          echo "Sending JSON Payload: $JSON_PAYLOAD"

          # Send the API request with verbose output
          curl -v -X POST "https://stanfordohs.pronto.io/api/v1/message.create" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.API_KEY }}" \
          -d "$JSON_PAYLOAD"
